namespace: public

resources:
  - ../base

patches:
  - target:
      kind: Deployment
      name: docker-debug
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: TRACING_URL
          value: http://otel-collector.monitoring.svc.cluster.local:9411
      - op: add
        path: /spec/template/spec/containers/1/env/-
        value:
          name: TRACING_URL
          value: http://otel-collector.monitoring.svc.cluster.local:9411
